# Book settings
# Learn more at https://jupyterbook.org/customize/config.html
page_titles: true
title: Chenoi AI Lab
author: Quechen YANG, with thank to my GF Becky Yu
logo: logo.jpg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off
  # timeout: 10
  # allow_errors: true
  # exclude_patterns:
  #   - 'programming_intro'
  #   - '90041_1'
  #   - '个贷违约预测'
  #   - '银行欺诈检测比赛'
  #   - '产品评论观点提取'
  #   - 'mental_cal'
  #   - 'Q_learning'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# launch_buttons:
#   notebook_interface: "classic"  # or "classic"
#   colab_url: "https://colab.research.google.com"

# # Information about where the book exists on the web
# repository:
#   url: https://github.com/executablebooks/jupyter-book  # Online location of your book
#   path_to_book: docs  # Optional path to your book, relative to the repository root
#   branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  # use_issues_button: true
  # use_repository_button: true
  google_analytics_id: G-X7Q6P8J04K
  announcement: "Welcome to chenoiAI Lab"
  use_multitoc_numbering: false
  comments:
    hypothesis: true
    utterances:
      repo: "iliiiiiili/chenoi"
      label: "✨💬✨"
      issue-term: "title"
      theme: "boxy-light"

sphinx:
  config:
    language: en
# #         html_theme: quantecon_book_theme

repository:
  url: https://github.com/iliiiiiili/chenoi # Online location of your book
  branch: gh-pages/
  # path_to_book              : /AI/RF/test.ipynb  # Optional path to your book, relative to the repository root

launch_buttons:
  thebe: true
